/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BreakoutRouteImport } from './routes/breakout'
import { Route as HangmanRouteImport } from './routes/hangman'
import { Route as SnakeRouteImport } from './routes/snake'
import { Route as TicTacToeRouteImport } from './routes/tic-tac-toe'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as CalendarWindowDayRouteImport } from './routes/calendar/window/$day'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BreakoutRoute = BreakoutRouteImport.update({
  id: '/breakout',
  path: '/breakout',
  getParentRoute: () => rootRouteImport,
} as any)
const HangmanRoute = HangmanRouteImport.update({
  id: '/hangman',
  path: '/hangman',
  getParentRoute: () => rootRouteImport,
} as any)
const SnakeRoute = SnakeRouteImport.update({
  id: '/snake',
  path: '/snake',
  getParentRoute: () => rootRouteImport,
} as any)
const TicTacToeRoute = TicTacToeRouteImport.update({
  id: '/tic-tac-toe',
  path: '/tic-tac-toe',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarWindowDayRoute = CalendarWindowDayRouteImport.update({
  id: '/calendar/window/$day',
  path: '/calendar/window/$day',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/breakout': typeof BreakoutRoute
  '/hangman': typeof HangmanRoute
  '/snake': typeof SnakeRoute
  '/tic-tac-toe': typeof TicTacToeRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/calendar/window/$day': typeof CalendarWindowDayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/breakout': typeof BreakoutRoute
  '/hangman': typeof HangmanRoute
  '/snake': typeof SnakeRoute
  '/tic-tac-toe': typeof TicTacToeRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/calendar/window/$day': typeof CalendarWindowDayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/breakout': typeof BreakoutRoute
  '/hangman': typeof HangmanRoute
  '/snake': typeof SnakeRoute
  '/tic-tac-toe': typeof TicTacToeRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/calendar/window/$day': typeof CalendarWindowDayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/breakout'
    | '/hangman'
    | '/snake'
    | '/tic-tac-toe'
    | '/demo/tanstack-query'
    | '/calendar/window/$day'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/breakout'
    | '/hangman'
    | '/snake'
    | '/tic-tac-toe'
    | '/demo/tanstack-query'
    | '/calendar/window/$day'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/breakout'
    | '/hangman'
    | '/snake'
    | '/tic-tac-toe'
    | '/demo/tanstack-query'
    | '/calendar/window/$day'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BreakoutRoute: typeof BreakoutRoute
  HangmanRoute: typeof HangmanRoute
  SnakeRoute: typeof SnakeRoute
  TicTacToeRoute: typeof TicTacToeRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  CalendarWindowDayRoute: typeof CalendarWindowDayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/breakout': {
      id: '/breakout'
      path: '/breakout'
      fullPath: '/breakout'
      preLoaderRoute: typeof BreakoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hangman': {
      id: '/hangman'
      path: '/hangman'
      fullPath: '/hangman'
      preLoaderRoute: typeof HangmanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/snake': {
      id: '/snake'
      path: '/snake'
      fullPath: '/snake'
      preLoaderRoute: typeof SnakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tic-tac-toe': {
      id: '/tic-tac-toe'
      path: '/tic-tac-toe'
      fullPath: '/tic-tac-toe'
      preLoaderRoute: typeof TicTacToeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar/window/$day': {
      id: '/calendar/window/$day'
      path: '/calendar/window/$day'
      fullPath: '/calendar/window/$day'
      preLoaderRoute: typeof CalendarWindowDayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BreakoutRoute: BreakoutRoute,
  HangmanRoute: HangmanRoute,
  SnakeRoute: SnakeRoute,
  TicTacToeRoute: TicTacToeRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  CalendarWindowDayRoute: CalendarWindowDayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
