/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GameGameRouteImport } from './routes/game/$game'
import { Route as CalendarWindowDayRouteImport } from './routes/calendar/window/$day'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GameGameRoute = GameGameRouteImport.update({
  id: '/game/$game',
  path: '/game/$game',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarWindowDayRoute = CalendarWindowDayRouteImport.update({
  id: '/calendar/window/$day',
  path: '/calendar/window/$day',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/game/$game': typeof GameGameRoute
  '/calendar/window/$day': typeof CalendarWindowDayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/game/$game': typeof GameGameRoute
  '/calendar/window/$day': typeof CalendarWindowDayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/game/$game': typeof GameGameRoute
  '/calendar/window/$day': typeof CalendarWindowDayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/game/$game' | '/calendar/window/$day'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/game/$game' | '/calendar/window/$day'
  id: '__root__' | '/' | '/game/$game' | '/calendar/window/$day'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GameGameRoute: typeof GameGameRoute
  CalendarWindowDayRoute: typeof CalendarWindowDayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/$game': {
      id: '/game/$game'
      path: '/game/$game'
      fullPath: '/game/$game'
      preLoaderRoute: typeof GameGameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar/window/$day': {
      id: '/calendar/window/$day'
      path: '/calendar/window/$day'
      fullPath: '/calendar/window/$day'
      preLoaderRoute: typeof CalendarWindowDayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GameGameRoute: GameGameRoute,
  CalendarWindowDayRoute: CalendarWindowDayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
